### PR TITLE
major version up

### PR DESCRIPTION
**Pull request by KazuCocoa**
- update version #273
- add setting locale method via setting app #271

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I'm not sure about it, but I think module version update happens when you execute npm publish and does not require a separate commit. Correct me if I'm wrong @imurchie

**Comment by imurchie** [comment]
Correct. Npm has a tool for changing the version and tagging correctly. In this case `npm version major` would do the work. The process is 
```
npm version major
git push --tags origin master
npm publish
```

**Comment by KazuCocoa** [comment]
thanks!
I've tagged. https://github.com/appium/appium-adb/releases/tag/v5.0.0

Could you add me to the project if it's no problem? @imurchie 
https://www.npmjs.com/~kazucocoa

**Comment by KazuCocoa** [comment]
I'll close this PR after publishing v5.0.0

**Comment by imurchie** [comment]
I've added you, so you should be able to publish `appium-adb`. Be _very_ careful doing so. Build should pass, use the `npm` tools to manage versioning and tagging. Thanks!

**Pull request closed without merging**
