### PR TITLE
Fix the error message if the command is of type string

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Addresses https://github.com/appium/appium/issues/10725

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Also I'm thinking about removing `isDeviceConnected` at all, since it is executed each time `adb shell` is invoked, which slows down test execution in general. adbExec is anyway supposed to fail if the device has been unexpectedly disconnected.

**Comment by mykola-mokhnach** [comment]
WDYT @imurchie ?

**Comment by imurchie** [comment]
How fast does `adb shell` fail if the device is not connected?

**Comment by mykola-mokhnach** [comment]
adbExec is set to retry once by default, but it is anyway faster than executing `adb devices` for each shell command

**Comment by imurchie** [comment]
Published in `appium-adb@6.10.0`.

**Pull request merged**
