### PR TITLE
fixed setWifiState and setDataState for API>19

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
This will resolve appium/appium#5256 and this will continue in appium/appium-android-driver#148.

Apologies for confusion.Have raised it here.

@imurchie @jlipps @TikhomirovSergey Please review. This fixes the API to work on all the Android API till API Level 23 (Tested from 19 to 23)

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
gulp test reports:
```
[22:07:47] Using gulpfile ~/AppiumRepo/appium-adb/gulpfile.js
[22:07:47] Starting 'test'...
[22:07:47] Starting 'transpile'...
[22:07:52] Finished 'transpile' after 5.67 s
[22:07:52] Starting 'unit-test'...
 132 -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_,------,
 0   -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_|   /\_/\ 
 14  -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-^|__( o .o) 
     -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-  ""  "" 

  132 passing (9s)
  14 pending

[22:08:01] Finished 'unit-test' after 9.04 s
[22:08:01] Starting 'transpile'...
[22:08:07] Finished 'transpile' after 5.34 s
[22:08:07] Starting 'e2e-test'...
killing process with command:sudo pkill -f emulator
Password:
info android-emu executing emulator -avd NEXUS_S_18_X86 -no-snapshot-load -no-snapshot-save -no-audio -netfast
info android-emu Waiting 15000 ms for emu...
info android-emu PANIC: HOME is defined but could not find NEXUS_S_18_X86.ini file in $HOME/.android/avd
info android-emu (Note: avd is searched in the order of $ANDROID_AVD_HOME,$ANDROID_SDK_HOME/.android/avd and $HOME/.android/avd)
info android-emu 
killing process with command:sudo pkill -f emulator
[22:08:13] Emulator closed too early, see emu logs for errors.
[22:08:13] Finished 'e2e-test' after 6.07 s
[22:08:13] Finished 'test' after 26 s
```

**Comment by imurchie** [comment]
Something weird went on with the CI in the shift to this PR. Can you update the commit and repush

```
git commit --amend -m "fixed setWifiState and setDataState for API>19"
git push -f origin wifiandData
```

Remote might be different for the second command, depending on your config.

**Comment by SrinivasanTarget** [comment]
Build looks green

**Comment by imurchie** [comment]
The one under "default" was having problems finding the commit.

https://team-appium.ci.cloudbees.com/view/Appium%20Libs/job/adb-e2e-android/

**Comment by jlipps** [comment]
👍

**Comment by SrinivasanTarget** [comment]
@imurchie Have re-comitted lets see

**Comment by TikhomirovSergey** [comment]
@imurchie @jlipps @SrinivasanTarget 
I think it is ok.

@SrinivasanTarget 
Have you checked the **None** mode? Client tests canct this error on Android >= 5.0.0

_java.lang.AssertionError: 
Expected :NONE
Actual   :DATA_

Maybe the fix should be present here too?

**Comment by SrinivasanTarget** [comment]
Fix is in already. We can test this in CI once CI issue is resolved.

**Comment by SrinivasanTarget** [comment]
@imurchie can you please fix CI? CI is not picking my changes yet.

**Comment by imurchie** [comment]
@SrinivasanTarget not sure why the build starting not working. But it seems to be in good order now, although it doesn't report back to GitHub (this is true in general :( :( :( ). 

Can you repush to this branch to trigger the build? The link will then be https://team-appium.ci.cloudbees.com/view/Appium%20Libs/job/adb-e2e-android/

**Comment by SrinivasanTarget** [comment]
@imurchie @jlipps Finally CI picked my changes and its pass here: https://team-appium.ci.cloudbees.com/view/Appium%20Libs/job/adb-e2e-android/154/

**Comment by SrinivasanTarget** [comment]
@imurchie @jlipps Is it good to merge? or any other suggestions?

**Comment by imurchie** [comment]
Looks good to me! Thanks for your patience!

**Comment by imurchie** [comment]
Published as `appium-adb@2.6.2`.

**Pull request merged**
