### PR TITLE
refactor!: Remove obsolete methods and properties

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
BREAKING CHANGE: The obsolete `emPort` property has been removed. Use `emulatorPort` instead
BREAKING CHANGE: The following coverage-related methods were removed as obsolete: `endAndroidCoverage`, `instrument`, `androidCoverage`
BREAKING CHANGE: The obsolete `jars` property has been removed.
BREAKING CHANGE: The obsolete `instrumentProc` property has been removed.

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Comment by snowkathi** [comment]
@mykola-mokhnach Can you point me any doc on why coverage is deprecated and not useful anymore? 
we are trying to achieve Instrumentation coverage for our mobile app but their methods are removed. Is there any go to alternative to these methods? 

BTW I am following this ref to achieve instrumentation  https://github.com/appium/appium/blob/1.19/docs/en/writing-running-appium/android/android-coverage.md

**Comment by snowkathi** [comment]
any update on this ? @mykola-mokhnach  @KazuCocoa

**Comment by snowkathi** [comment]
@mykola-mokhnach @KazuCocoa can you help us to get update on this ?

**Comment by KazuCocoa** [comment]
You could do the same thing via https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-shell if you'd like to try the command out

**Pull request merged**
