### PR TITLE
Fix returned value for getAndroidPlatformAndPath to avoid deconstruction error

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Addresses https://github.com/appium/appium/issues/8773

### CODE REVIEW

**Comment by imurchie** [comment]
What is wrong with updating `getAndroidPlatformAndPath` to return `{platform: null, platformPath: null}`, and leaving the calling code like it is?

**Comment by mykola-mokhnach** [comment]
@imurchie It will require more changes, since functional and unit tests rely on it. I've just selected the shortest way ;)

**Comment by imurchie** [comment]
I've done that work under https://github.com/appium/appium-adb/pull/241

**Comment by mykola-mokhnach** [comment]
Thanks @imurchie

**Pull request closed without merging**
