### PR TITLE
Add support for a 'waitDuration' option in startApp

### PR DESCRIPTION
**Pull request by JamieEdge**
This might be required for https://github.com/appium/appium/issues/780.

### CODE REVIEW

**Comment by chrigrahcisco** [comment]
Can you provide details on how to exercise the waitDuration option?

**Comment by edgy360** [comment]
It's been a while since I directly used appium-adb, so not sure if it has changed, but you should just need to set this as part of the launch options.

**Comment by chrigrahcisco** [comment]
I happen to be using Appium.app   and see no such option, nor any documentation of a server flag, assuming one exists.

**Comment by edgy360** [comment]
This was a pull request into appium-adb rather than Appium so it didn’t expose a server flag. It would need to be added into the main Appium source too for that functionality to exist if it hasn’t been already.

**Pull request merged**
