### PR TITLE
Fix for https://github.com/appium/appium-adb/issues/91 related to quoting when using "optionalIntentArguments" capability

### PR DESCRIPTION
**Pull request by jeanbaptistelab**
…ting when using "optionalIntentArguments" capability

### CODE REVIEW

**Comment by jlipps** [comment]
@moizjv this should be fixed automatically by using teen_process in 1.5, no?

**Comment by moizjv** [comment]
@jlipps yes i want to think so but i would still test it as this seems to be issue were we want to pass JSON as argument to spawn ( `adb shell "am start ... -option someJSON"` )  I will test and get back

**Comment by jeanbaptistelab** [comment]
@jlipps actually, I don't think using teen_process alone would solve this issue, which is really related to the way the "adb shell am start -option <args>" handles the quoting of args. I believe my fix or one of the sort will still be needed...

**Comment by jlipps** [comment]
@jeanbaptistelab are you able to work on a fix (and test) on the 2.0 branch? you'll notice it's quite different in terms of the JS ^_^

**Comment by jeanbaptistelab** [comment]
@jlipps I'll take a look at the 2.0 branch...

**Comment by jlipps** [comment]
@jeanbaptistelab have you had a chance to take a look at this?

**Pull request closed without merging**
