### PR TITLE
chore: Make sure settings app is running before broadcasting to it

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Related to https://github.com/appium/appium-uiautomator2-driver/pull/556/files#r1002775545

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Hm, not yet? The below is after terminating  the settings app. I haven't read the log/track it well yet.

```
[HTTP] --> GET /wd/hub/session/d3a732bf-d0bf-4dad-831f-f64f73de6aac/location
[HTTP] {}
[debug] [AndroidUiautomator2Driver@7fb5 (d3a732bf)] Calling AppiumDriver.getGeoLocation() with args: ["d3a732bf-d0bf-4dad-831f-f64f73de6aac"]
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s D0AA002182JC0202126 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
[debug] [ADB] Starting Appium Settings app
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s D0AA002182JC0202126 shell dumpsys window displays'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s D0AA002182JC0202126 shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s D0AA002182JC0202126 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
[debug] [ADB] Activating 'io.appium.android.apis'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s D0AA002182JC0202126 shell cmd package resolve-activity --brief io.appium.android.apis'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s D0AA002182JC0202126 shell am start-activity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.android.apis/.ApiDemos'
[debug] [ADB] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.appium.android.apis/.ApiDemos }
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s D0AA002182JC0202126 shell am broadcast -n io.appium.settings/.receivers.LocationInfoReceiver -a io.appium.settings.location'
[debug] [AndroidUiautomator2Driver@7fb5 (d3a732bf)] Encountered internal error running command: Error: Cannot parse the actual location values from the command output: Broadcasting: Intent { act=io.appium.settings.location flg=0x400000 cmp=io.appium.settings/.receivers.LocationInfoReceiver }
[debug] [AndroidUiautomator2Driver@7fb5 (d3a732bf)] Broadcast completed: result=0, data=""
[debug] [AndroidUiautomator2Driver@7fb5 (d3a732bf)]     at ADB.getGeoLocation (/Users/kazuaki/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-adb/lib/tools/settings-client-commands.js:311:11)
[debug] [AndroidUiautomator2Driver@7fb5 (d3a732bf)]     at AndroidUiautomator2Driver.getGeoLocation (/Users/kazuaki/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/network.js:168:43)
[HTTP] <-- GET /wd/hub/session/d3a732bf-d0bf-4dad-831f-f64f73de6aac/location 500 931 ms - 1017
[HTTP]
```

**Comment by mykola-mokhnach** [comment]
strange, this should basically be the same as restarting settings app manually. Is there another reason in such behavior?

**Comment by KazuCocoa** [comment]
Potentially could be, I wonder if it is more settings app internal something (e.g. it needs to wait a bit after the launch) now since I issued https://github.com/appium/appium-uiautomator2-driver/pull/556#discussion_r1002775545 command call by my CLI env one by one locally. It could take in 1 sec each command.
I'll take a look deeper later

**Comment by KazuCocoa** [comment]
Perhaps.. it was something timing issue in the getting location data in the settings app. Sometimes this PR worked without additional retry after terminating the settings app. Sometimes it needed to re-call the `driver.location` once, but the 2nd one succeeded 100% while without this PR never succeeded.

I haven't dug into the settings app itself, but perhaps we can do something.

Anyway, this PR itself made this location sruff

**Review by KazuCocoa — APPROVED** [review]

**Pull request merged**
