### PR TITLE
add startUri method so people can navigate directly into a deep view

### PR DESCRIPTION
**Pull request by jlipps**
please review @moizjv @imurchie

### CODE REVIEW

**Comment by imurchie** [comment]
Looks good. Not sure about the e2e failure. Never seen `mCurrentFocus=Window{b241db78 u0 Keyguard}`.

**Comment by jlipps** [comment]
ok attempting to fix it

**Comment by jlipps** [comment]
fixed!

**Comment by jlipps** [comment]
appium-adb 2.2.0 published

**Pull request merged**
