### PR TITLE
Correct Regex for deviceNotFoundError

### PR DESCRIPTION
**Pull request by crashbell**
The exact error is `error: device '3801b560347ac200' not found`. So I change the Regex to match with that error.

### CODE REVIEW

**Comment by imurchie** [comment]
Thanks for this! The regex does seem to need to be that way. Are we sure that for earlier versions of adb this was always the case? The regex could be made to handle the old behaviour as well as the new (i.e., catch `error: device 'blah-blah-blah' not found` as well as `error: device not found`)

https://regex101.com/r/rQ1pI7/1

**Comment by crashbell** [comment]
@imurchie your regex makes more sense. I update the code.

**Comment by imurchie** [comment]
Excellent! There is no need, however, for the escaping around the single quotes.

**Comment by crashbell** [comment]
I have removed them.

**Comment by imurchie** [comment]
Weird. jshint clearly is confused. But since it seems that it will only be a space after the device name, the `\s` could just be a single space (i.e., `let deviceNotFoundError = new RegExp("error: device ('.+' )?not found", "i").test(e);`) You can run, on the command line, `gulp jshint` to see if it passes linting.

Sorry for the mix up. :(

**Comment by crashbell** [comment]
I updated it, now it passed the jshint checker.

**Comment by imurchie** [comment]
Functional tests are good to go, too: https://team-appium.ci.cloudbees.com/view/Appium%20Libs/job/adb-e2e-android/159/console

**Comment by imurchie** [comment]
Thanks for fixing this! And for your patience!

**Comment by crashbell** [comment]
@imurchie Thanks for reviewing this :)

**Comment by imurchie** [comment]
Published as `appium-adb@2.6.3`

**Pull request merged**
