### PR TITLE
Grant permissions on install

### PR DESCRIPTION
**Pull request by imurchie**
Use `-g` to grant all the permissions from the manifest, upon install.

Addresses https://github.com/appium/appium/issues/6928 and https://github.com/appium/appium/issues/6091

### CODE REVIEW

**Comment by imurchie** [comment]
Functional tests passing: https://team-appium.ci.cloudbees.com/view/Appium%20Libs/job/adb-e2e-android/180/console

**Comment by amedvedjev** [comment]
hi. tested fix and it does not work.
LOG: 

> ["-P",5037,"-s","LGH8155e9892e6","uninstall","ee.poco.alpha"]
> ["-P",5037,"-s","LGH8155e9892e6","shell","pm","install","-rg","/data/local/tmp/8740dcad4f7f392a2140b51b05f704fa.apk"]

i tested it manually and found out strange thing. when we install app like:

> adb install -g or adb install -gr - ALL is fine

but

> adb install -rg - Permissions not granted.

**Comment by imurchie** [comment]
Very weird.

**Comment by imurchie** [comment]
`appium-adb@2.6.15` has the parameters adjusted. Can you try that @amedvedjev ?

**Comment by amedvedjev** [comment]
@imurchie it is little better now.
When i am doing clean install or fullReset all is fine. But when i do fastReset permissions appear again. fastReset is quite important feature to quickly reset app without taking long time reinstall.

fullReset:
```
capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);
capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
```
fastReset:
```
capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
```

LOGS:

> [AndroidDriver] Apk is already on remote and installed, resetting
> [debug] [AndroidDriver] Running fast reset (stop and clear)
> [debug] [ADB] Getting connected devices...
> [debug] [ADB] 1 device(s) connected
> [debug] [ADB] Running '/Users/Aleksei/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGH8155e9892e6","shell","am","force-stop","ee.poco.alpha"]
> [debug] [ADB] Getting connected devices...
> [debug] [ADB] 1 device(s) connected
> [debug] [ADB] Running '/Users/Aleksei/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGH8155e9892e6","shell","pm","clear","ee.poco.alpha"]

**Comment by amedvedjev** [comment]
why not to add with reset all permissions like:
`adb -d shell pm grant com.some.package android.permission.WRITE_SECURE_SETTINGS` - ?

**Comment by imurchie** [comment]
Feel free to implement that. I don't have a way to verify that things work.

**Pull request merged**
