### PR TITLE
Fix many problems for Nougat

### PR DESCRIPTION
**Pull request by imurchie**
adb seems to have gotten worse.

The only problem I'm still seeing is with `adb stop`, which now requires root access but when adb is run with root it does nothing. So rebooting is messed up.

### CODE REVIEW

**Comment by imurchie** [comment]
Addresses:

https://github.com/appium/appium/issues/6858
https://github.com/appium/appium/issues/6779
https://github.com/appium/appium/issues/6776
https://github.com/appium/appium/issues/6665
https://github.com/appium/appium/issues/6850

Maybe others.

**Comment by imurchie** [comment]
#171 seemed to be going nowhere.

**Comment by imurchie** [comment]
Updated to include parts of #171.

**Comment by imurchie** [comment]
Published in `appium-adb@2.6.13`.

**Comment by vchimev** [comment]
Thanks, @imurchie!

We updated to `appium-adb@2.6.13` and it seems we are able to run our tests on Android Emulator API 24.

**Comment by Mygod** [comment]
I updated to 2.6.13 and is still getting this error:

```[UiAutomator] Error while killing uiAutomator: Error: Unable to kill uiautomator processes. Original error: Unable to get pids for uiautomator. Orginial error: Could not extract PID from ps output: bad pid 'uiautomator'```

**Comment by imurchie** [comment]
How did you update? Is the update being actually run?

**Comment by Mygod** [comment]
@imurchie I opened an issue at #177.

I update by running `sudo npm install -g appium@2.0.0-beta3`.

**Comment by hardik-d** [comment]
@imurchie after running npm install appium-adb@2.6.13 from appium folder i started getting some init failure and appium server won't start? am i missing more steps?

**Comment by imurchie** [comment]
I have no idea. More information is needed if you want me to say anything.

**Comment by hardik-d** [comment]
so i am on appium 1.4.13 and running test on android 7 emulator i got:

info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 push "/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
info: [debug] Pushing settings apk to device...
info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 install "/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/settings_apk/settings_apk-debug.apk"
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
warn: UiAutomator did not shut down fast enough, calling it gone
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 install "/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/settings_apk/settings_apk-debug.apk"
Failed to install /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/settings_apk/settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]

info: [debug] Error: Command failed: /bin/sh -c /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 install "/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/settings_apk/settings_apk-debug.apk"
Failed to install /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/settings_apk/settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 install \"/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/settings_apk/settings_apk-debug.apk\"\nFailed to install /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/settings_apk/settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]\n)","killed":false,"code":1,"signal":null,"cmd":"/bin/sh -c /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 install \"/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/settings_apk/settings_apk-debug.apk\"","origValue":"Command failed: /bin/sh -c /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 install \"/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/settings_apk/settings_apk-debug.apk\"\nFailed to install /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/build/settings_apk/settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 13048.697 ms - 1301 

than i ran npm install appium-adb@2.6.13 from appium directory and then starting appium i get:

error: uncaughtException: Cannot read property 'init' of undefined date=Tue Nov 15 2016 08:45:39 GMT-0800 (PST), pid=84268, uid=501, gid=20, cwd=/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium, execPath=/Users/hardik/.nvm/versions/node/v5.0.0/bin/node, version=v5.0.0, argv=[/Users/hardik/.nvm/versions/node/v5.0.0/bin/node, /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/bin/appium.js], rss=113201152, heapTotal=89747968, heapUsed=52716272, loadavg=[1.681640625, 2.1640625, 2.521484375], uptime=1593246, trace=[column=11, file=/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/devices/android/adb.js, function=, line=6, method=null, native=false, column=26, file=module.js, function=Module._compile, line=425, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=432, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=311, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=366, method=require, native=false, column=17, file=module.js, function=require, line=385, method=null, native=false, column=11, file=/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/devices/android/android-common.js, function=, line=15, method=null, native=false, column=26, file=module.js, function=Module._compile, line=425, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=432, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=311, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=366, method=require, native=false, column=17, file=module.js, function=require, line=385, method=null, native=false, column=21, file=/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/devices/android/android.js, function=, line=14, method=null, native=false, column=26, file=module.js, function=Module._compile, line=425, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=432, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=311, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=366, method=require, native=false, column=17, file=module.js, function=require, line=385, method=null, native=false, column=15, file=/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/appium.js, function=, line=10, method=null, native=false, column=26, file=module.js, function=Module._compile, line=425, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=432, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=311, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=366, method=require, native=false, column=17, file=module.js, function=require, line=385, method=null, native=false, column=14, file=/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/server/main.js, function=, line=54, method=null, native=false, column=26, file=module.js, function=Module._compile, line=425, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=432, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=311, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=366, method=require, native=false, column=17, file=module.js, function=require, line=385, method=null, native=false, column=15, file=/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/bin/appium.js, function=, line=14, method=null, native=false, column=26, file=module.js, function=Module._compile, line=425, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=432, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=311, method=Module._load, native=false], stack=[TypeError: Cannot read property 'init' of undefined,     at Object.<anonymous> (/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/devices/android/adb.js:6:11),     at Module._compile (module.js:425:26),     at Object.Module._extensions..js (module.js:432:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:311:12),     at Module.require (module.js:366:17),     at require (module.js:385:17),     at Object.<anonymous> (/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/devices/android/android-common.js:15:11),     at Module._compile (module.js:425:26),     at Object.Module._extensions..js (module.js:432:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:311:12),     at Module.require (module.js:366:17),     at require (module.js:385:17),     at Object.<anonymous> (/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/devices/android/android.js:14:21),     at Module._compile (module.js:425:26),     at Object.Module._extensions..js (module.js:432:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:311:12),     at Module.require (module.js:366:17),     at require (module.js:385:17),     at Object.<anonymous> (/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/appium.js:10:15),     at Module._compile (module.js:425:26),     at Object.Module._extensions..js (module.js:432:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:311:12),     at Module.require (module.js:366:17),     at require (module.js:385:17),     at Object.<anonymous> (/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/server/main.js:54:14),     at Module._compile (module.js:425:26),     at Object.Module._extensions..js (module.js:432:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:311:12),     at Module.require (module.js:366:17),     at require (module.js:385:17),     at Object.<anonymous> (/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/bin/appium.js:14:15),     at Module._compile (module.js:425:26),     at Object.Module._extensions..js (module.js:432:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:311:12)]

**Comment by imurchie** [comment]
There is no way that the latest Android will work with 1.4.16, unfortunately.

**Comment by hardik-d** [comment]
That's sad, with latest appium lacking key ios10 support not sure of the upgrade path. Does appium 1.6 support backwards compatibility for older ios automation library? for e.g. can i run my appium tests on ios 9.3 and below on older automation library and not XCUITest?

**Comment by imurchie** [comment]
Yes. Appium 1.6.x supports everything that was supported, plus adds XCUITest support so that iOS 10 can be handled. Earlier versions will not be able to work with iOS 10 at all.

**Comment by hardik-d** [comment]
@imurchie that is awesome will upgrade and give it a shot. 1.6.1 beta promises lot of the things i found were missing, fingers crossed!

**Comment by rkavalap** [comment]
@imurchie  side note question. 
Should version of adb executing on host machine where appium executes and adb deamon executing on the device under test to match ? just to keep track of backwards/forwards compatibility of adb versioning.

**Comment by imurchie** [comment]
I don't know. I've never heard of any problems related to that.

**Pull request merged**
