### PR TITLE
feat: Added support for activities with multilingual chars 

### PR DESCRIPTION
**Pull request by tomaskatz96**

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@tomaskatz96 Please make sure your local git account email address is the same that has been used to sign CLA. You may use https://stackoverflow.com/questions/37805621/change-email-address-in-git for the reference. It would be enough to just perform one commit with the correct email to make the automatic CLA validation happy.

**Comment by tomaskatz96** [comment]
@mykola-mokhnach  committed with the right mail and still not authorized for some reason

**Comment by KazuCocoa** [comment]
What about the steps below?

1. git rebase your two commit in this PR to one
2. git commit and run `amend` with `author` with your signed email address

https://stackoverflow.com/questions/3042437/how-can-i-change-the-commit-author-for-a-single-commit

Then, you may need to do a force push to the branch once

**Comment by KazuCocoa** [comment]
Hm, what email did you use for the sign to CLA? `tomas.katz@mail.huji.ac.il`...? (from the latest git log)
If so, could you re-create a PR with the latest branch again?

**Comment by tomaskatz96** [comment]
@KazuCocoa Will try to open the PR again

**Pull request closed without merging**
