### PR TITLE
update version

### PR DESCRIPTION
**Pull request by KazuCocoa**
To apply _add setting locale method via setting app #271_, this PR bump up the version number.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Did we change any public interfaces there? if so then the major version number should be updated.

**Comment by KazuCocoa** [comment]
I've added a new public interface, `setDeviceSysLocaleViaSettingApp`, and `setDeviceLocale` works as same as 4.1.0.

**Comment by KazuCocoa** [comment]
ah, but `setDeviceLocale` has validation from now. So, it's safe to update major version, I felt.
I'll create new PR.

**Comment by imurchie** [comment]
The version in `package.json` should not be manually changed. It is changed (and committed) as part of the publish process.

**Pull request closed without merging**
